# Generated by Django 5.0 on 2024-01-06 14:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 1, 6, 14, 14, 10, 287447, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=datetime.datetime(2024, 1, 6, 14, 14, 23, 94794, tzinfo=datetime.timezone.utc), upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 1, 6, 14, 15, 55, 390408, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
        ),
    ]
